#!/bin/bash

# make user software dir
mkdir -p ${HOME}/.local/bin

## install cosparallel

(cd ~ \
&& svn checkout svn://svn.code.sf.net/p/cosparallel/code/trunk cosparallel-code \
&& cd cosparallel-code \
&& ./configure \
&& make \
&& mv cos ${HOME}/.local/bin \
&& cd extras \
&& make \
&& mv maximal_cliques ${HOME}/.local/bin) && rm -rf cosparallel-code

## install tinytex & phantomjs

R -e 'tinytex::install_tinytex(dir="~/.local/TinyTex");webshot::install_phantomjs()' \
&& mv ${HOME}/bin/* ${HOME}/.local/bin \
&& rm -rf ${HOME}/bin

## install patched stargazer to integrate bookdown

git config user.email 'brooksambrose@gmail.com' \
&& git clone https://github.com/cran/stargazer \
&& cd stargazer \
&& git remote add -f rpatch https://github.com/brooksambrose/stargazer_bookdown \
&& git merge -m'play well with bookdown' rpatch/master \
&& cd .. && R -e 'devtools::install_git("stargazer")' \
&& rm -rf stargazer


## install uclathes document class and citation style

git clone -b 2.0 https://github.com/louis925/uclathes \
&& (cd uclathes && git checkout a4c74df) \
&& mkdir -p $(kpsewhich -var-value=TEXMFHOME)/tex/latex/uclathes \
&& mv uclathes/*.cl[so] $_ \
&& mkdir -p $(kpsewhich -var-value=TEXMFHOME)/bibtex/bst/uclathes \
&& mv uclathes/*.bst $_ \
&& rm -rf uclathes
