#!/bin/bash
#R CMD javareconf

## Install cosparallel

(cd ~/ \
	&& svn checkout svn://svn.code.sf.net/p/cosparallel/code/trunk cosparallel-code \
	&& cd cosparallel-code \
	&& ./configure \
	&& make \
	&& cd extras \
	&& make)

## tinytex

R -e 'tinytex::install_tinytex()'

mkdir -p ${HOME}/local/bin && mv ${HOME}/bin/* ${HOME}/local/bin && rm -rf ${HOME}/bin