#!/bin/bash
#R CMD javareconf

## Install cosparallel

(cd ~/ \
	&& svn checkout svn://svn.code.sf.net/p/cosparallel/code/trunk cosparallel-code \
	&& cd cosparallel-code \
	&& ./configure \
	&& make \
	&& cd extras \
	&& make)

## run install.R since r2d didn't do it!

R CMD install.R

apt-get update && \
apt-get install --yes --no-install-recommends xauth xvfb && \
apt-get purge && \
apt-get clean && \
rm -rf /var/lib/apt/lists/*

xvfb-run R CMD -e '{install.packages(c("cairoDevice","RQDA"));warnings()}'

	